### ISSUE TITLE
Break up prototype into React components

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/application-creator-landingpage#3]
Use TypeScript

**Comment by quintesse** [comment]
Btw, I would suggest to still try to build it using easily copyable parts or modules instead of something more "monolithic". That way we can create a frontend application that only contains the necessary parts to show the features the user requested. If it were more monolithic (ie it would contain all possible landing pages) users might have trouble separating the wheat from the chaff?

**Comment by ALRubinger** [comment]
I *think* I agree on the modular approach, but for now I'm just looking to make the modules locally and bring them all together in the same monolithic app.  For instance:

`import HealthCheck from './components/HealthCheckComponent'`

...and, in the master page...

`if(this.hasHealthCheck()) { <HealthCheck /> }`

...where we assume a `components` folder to put these.

I figure we can split this apart and figure how we deliver the thing in stages, and this seems like a logical next step to me, no?

**Comment by quintesse** [comment]
On the other hand the idea of having a single externally managed app/project that could just be provisioned into the user's project has a strong appeal. (It takes away the problem how to provision two services from a single code-base). I'm just somewhat "worried" that this might make it more difficult to attract community contributions.

> this seems like a logical next step to me, no?

Yes, certainly!

**Comment by ALRubinger** [comment]
f9e3fb791e5fd9ea72c37d12ebaf5a41d93ea9ff
